# Generated by Django 4.2.30 on 2026-06-23 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age_years', models.PositiveSmallIntegerField(default=0)),
                ('age_months', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], max_length=10)),
                ('color_markings', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('temperament', models.TextField(blank=True)),
                ('good_with_kids', models.BooleanField(default=False)),
                ('good_with_pets', models.BooleanField(default=False)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('is_neutered', models.BooleanField(default=False)),
                ('medical_notes', models.TextField(blank=True)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('pending', 'Pending'), ('unavailable', 'Unavailable')], default='available', max_length=15)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pets.models.pet_photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.pet')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
