# Generated by Django 4.2.30 on 2026-06-23 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('housing_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('other', 'Other')], max_length=15)),
                ('owns_or_rents', models.CharField(choices=[('owns', 'Owns'), ('rents', 'Rents')], max_length=10)),
                ('landlord_contact', models.CharField(blank=True, max_length=200)),
                ('household_members', models.PositiveSmallIntegerField(default=1)),
                ('has_other_pets', models.BooleanField(default=False)),
                ('other_pets_desc', models.CharField(blank=True, max_length=300)),
                ('prev_pet_experience', models.TextField(blank=True)),
                ('reason_for_adoption', models.TextField()),
                ('agrees_to_home_visit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('admin_remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pets.pet')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('pet', 'applicant')},
            },
        ),
    ]
